from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.adminsignin,name='signinadmin'),
    path('adminhome',views.adminhome,name='adminhome'),
    path('adminlogout',views.logoutadmin,name='adminlogout'),
    path('product',views.product,name='product'),
    path('addproduct',views.addproduct,name='addproduct'),
    path('userlist',views.user_list,name='userlist'),
    path('block_user/<int:id>',views.block_user,name='block_user'),
    path('deleteproduct/<int:id>',views.deleteproduct,name='deleteproduct'),
    path('categoryList/',views.categoryList,name='categorylist'),
    path('addcategory',views.addcategory,name='addcategory'),
    path('addsubcategory',views.addsubcategory,name='addsubcategory'),
    path('editproduct/<int:id>',views.editproduct,name='editproduct'),
    path('editcategory/<int:id>',views.editcategory,name='editcategory'),
    path('deletecategory/<int:id>',views.deletecategory,name='deletecategory'),
    path('variationlist',views.variationlist,name='variationlist'),
    path('addvariation',views.addvariation,name='addvariation'),
    path('editvariation/<int:id>',views.editvariation,name='editvariation'),
    path('deletevariation/<int:id>',views.deletevariation,name='deletevariation'),
    path('orderlist',views.orderlist,name='orderlist'),
    path('orderdetail/<int:id>',views.orderdetail,name='orderdetail'),
    path('product_change_status/<int:id>',views.product_change_status,name='product_change_status'),
    path('view_coupon',views.view_coupon,name='view_coupon'),
    path('DeleteCoupon/<int:id>',views.DeleteCoupon,name='DeleteCoupon'),
    path('addcopnredirect',views.addcopnredirect,name='addcopnredirect'),
    path('AddCoupon',views.AddCoupon,name='AddCoupon'),
    path('ListOffer',views.ListOffer,name='ListOffer'),
    path('cateofferdelete/<int:id>',views.cateofferdelete,name='cateofferdelete'),
    path('prodofferdelete/<int:id>',views.prodofferdelete,name='prodofferdelete'),
    path('addcatoffer',views.addcatoffer,name='addcatoffer'),
    path('addprooffer',views.addprooffer,name='addprooffer'),
    # path('salesreport',views.salesreport,name='salesreport'),
    path('export_pdf',views.export_pdf,name='export_pdf'),
    # path('export_excel_year',views.export_excel_year,name='export_excel_year'),
    # path('create-pdf', views.pdf_report_create, name='create-pdf'),
    # path('export_excel',views.export_excel,name='export_excel'),
    # path('export_excel_year',views.export_excel_year,name='export_excel_year'),    
    # path('invoice/<int:order_number>',views.invoice,name="invoice_admin"),
    # path('check-pdf',views.pdf_check,name="pdfcheck"),
    # path('monthly_report/<int:date>/',views.monthly_report,name='monthly_report'),
    # path("yearly_report/<int:date>/",views.yearly_report,name="yearly_report"),
    # path("date_range",views.date_range,name="date_range"),
    path("salesreport",views.salesreport,name="salesreport"),
    path("monthly_report/<int:date>/",views.monthly_report,name="monthly_report"),
    path("yearly_report/<int:date>/",views.yearly_report,name="yearly_report"),
    path("date_range",views.date_range,name="date_range"),
    path('download_excel/',views.download_excel,name='download_excel'),
    path('download_csv/',views.download_csv,name='download_csv'),
    
]