# Generated by Django 4.0.7 on 2022-09-27 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0004_offerproduct_offercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercategory',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
