# Generated by Django 4.0.7 on 2022-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categories_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/categories'),
        ),
    ]
