# Generated by Django 4.0.7 on 2022-09-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
