# Generated by Django 4.0.7 on 2022-09-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0002_alter_coupon_discount'),
        ('order', '0003_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra.coupon'),
        ),
    ]
