# Generated by Django 4.0.7 on 2022-09-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_coupon'),
        ('products', '0002_remove_coupon_is_expired_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
